services:
  - type: web
    name: democracy-with-ease
    runtime: python-3.14
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn simplevote.wsgi:application
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: DJANGO_SETTINGS_MODULE
        value: simplevote.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "democracy-with-ease.onrender.com"
      - key: DATABASE_URL
        value: "postgresql://favour_3c5k_user:EYR5Tm0JVL3GarTQAgP8QfHpzYi8f839@dpg-d836463tqb8s73dca6v0-a.oregon-postgres.render.com/favour_3c5k"
