# Generated by Django 4.2.29 on 2026-05-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('poll_created', 'Poll Created'), ('vote_cast', 'Vote Cast'), ('poll_ended', 'Poll Ended'), ('profile_updated', 'Profile Updated'), ('login', 'Login'), ('logout', 'Logout'), ('registration', 'Registration'), ('admin_registration', 'Admin Registration')], max_length=50),
        ),
    ]
